#!/usr/bin/env python3
"""Stage 6 - assemble the deliverable.

Turns the stage-2 output into a database that is actually ready for a
mass-spectrometry search, and packages it with the provenance a
collaborator needs to reproduce it.

Steps:
  1. Cross-class deduplication. Stage 2 deduplicates within a variant
     class, so one sequence can still appear under two classes. Identical
     sequences are merged, keeping the most informative class and
     recording the others in the header.
  2. Peptide-level novelty. For each entry, count the tryptic peptides
     absent from the reference proteome, and how many of those actually
     span the variant residue. An entry contributing zero novel peptides
     enlarges the search space without adding information; it can be
     dropped with --drop-non-novel.
  3. Optional reference appending. A variant peptide is only
     interpretable next to its wild-type counterpart.
  4. Optional decoys, generated by the same process as the target so FDR
     estimation models the same peptide space.
  5. MANIFEST.txt with SHA-256 of every file, plus METHODS.md.

Usage:
  python src/v2p/stages/06_package_release.py \
      --fasta   results/fasta/HCC1395_variant_proteins.uniprot.representative.fasta \
      --uniprot ref/uniprot_human_SP.fasta \
      --outdir  release --decoy pseudo_reverse --append-reference
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import re
import shutil
import sys
from collections import Counter, defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from v2p.peptides import (                                 # noqa: E402
    DECOY_METHODS, digest, novel_peptides, reference_peptide_space,
    variant_spanning_peptides,
)
from v2p.provenance import RunLogger, sha256               # noqa: E402
from v2p.validate import UniProtDB                         # noqa: E402

# Which class label wins when one sequence arises from several variants.
CLASS_PRIORITY = ["FUSION", "INDEL", "SNV", "MNV", "RNA_EDITING",
                  "AS_SE", "AS_RI", "AS_MX", "AS_A3", "AS_A5",
                  "AS_AF", "AS_AL", "REFERENCE"]

# Plain-language description of every file the split produces, so nobody
# has to decode "AS_A3" from a filename.
CLASS_DESC = {
    "SNV": ("Somatic single-nucleotide variants",
            "One amino-acid substitution, a premature stop, or a lost stop, "
            "from the high-confidence somatic SNV call set."),
    "MNV": ("Somatic multi-nucleotide variants",
            "Two or more adjacent substitutions changing one or more codons."),
    "INDEL": ("Somatic insertions and deletions",
              "In-frame insertions and deletions change residues locally; "
              "frameshifts replace the entire C-terminus with novel sequence."),
    "RNA_EDITING": ("A-to-I RNA editing sites",
                    "ADAR converts adenosine to inosine, which the ribosome "
                    "reads as guanosine. Only codon-changing sites appear here; "
                    "the DNA is unchanged, so these proteoforms exist only at "
                    "the RNA and protein level."),
    "FUSION": ("Gene fusions",
               "Chimeric proteins: the 5' partner up to the breakpoint joined "
               "to the 3' partner after it. The header records whether the "
               "junction preserves the codon boundary and whether the 3' "
               "partner continues in its own reading frame."),
    "AS_SE": ("Alternative splicing — skipped exon",
              "A cassette exon is included or excluded, adding or removing an "
              "internal block of residues."),
    "AS_RI": ("Alternative splicing — retained intron",
              "An intron stays in the mature transcript. It usually introduces "
              "a premature stop, so check the NMD flag."),
    "AS_MX": ("Alternative splicing — mutually exclusive exons",
              "Exactly one of two alternative exons is used."),
    "AS_A3": ("Alternative splicing — alternative 3' splice site",
              "A different acceptor shifts the start of an exon."),
    "AS_A5": ("Alternative splicing — alternative 5' splice site",
              "A different donor shifts the end of an exon."),
    "AS_AF": ("Alternative splicing — alternative first exon",
              "A different first exon, so a different start codon and a "
              "different N-terminus. The largest class in this dataset."),
    "AS_AL": ("Alternative splicing — alternative last exon",
              "A different final exon, so a different C-terminus."),
    "REFERENCE": ("Wild-type counterparts",
                  "The unmodified protein of each transcript carrying a "
                  "variant. A variant peptide is only interpretable next to "
                  "its wild-type counterpart, which is why these are here."),
    "REFERENCE_PROTEOME": ("Full reference proteome",
                           "The supplied UniProt SwissProt entries, verbatim "
                           "and unmodified, appended for database search."),
    "UNCLASSIFIED": ("Unclassified",
                     "No variant type could be read from the header — report "
                     "this, it should not happen."),
}


def read_fasta(path: Path):
    name, buf = None, []
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            line = line.rstrip("\n")
            if line.startswith("#"):
                continue
            if line.startswith(">"):
                if name is not None:
                    yield name, "".join(buf)
                name, buf = line, []
            elif name is not None:
                buf.append(line.strip())
    if name is not None:
        yield name, "".join(buf)


def kv(header: str) -> dict[str, str]:
    out = {}
    for tok in header.split():
        if "=" in tok:
            k, v = tok.split("=", 1)
            out[k] = v
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--fasta", required=True, help="stage 2 output")
    ap.add_argument("--uniprot", required=True, help="reference proteome")
    ap.add_argument("--outdir", default="release")
    ap.add_argument("--logdir", default="logs")
    ap.add_argument("--name", default="HCC1395_variant_proteome")
    ap.add_argument("--decoy", choices=sorted(DECOY_METHODS) + ["none"],
                    default="none")
    ap.add_argument("--decoy-prefix", default="DECOY_")
    ap.add_argument("--append-reference", action="store_true",
                    help="append the full reference proteome verbatim")
    ap.add_argument("--drop-non-novel", action="store_true",
                    help="drop entries contributing no novel tryptic peptide")
    ap.add_argument("--drop-nmd", action="store_true",
                    help="drop entries flagged NMD=likely")
    ap.add_argument("--missed-cleavages", type=int, default=2)
    ap.add_argument("--min-pep-len", type=int, default=6)
    ap.add_argument("--max-pep-len", type=int, default=50)
    ap.add_argument("--split-by-class", action="store_true",
                    help="also write one FASTA per variant type into "
                         "by_class/, so each evidence type can be searched "
                         "or shared independently")
    ap.add_argument("--no-sequence-column", action="store_true",
                    help="omit the sequence from the entry table")
    ap.add_argument("--extra-file", action="append", default=[],
                    help="repeatable; copy into the release (logs, QC, code)")
    args = ap.parse_args()

    out = Path(args.outdir)
    out.mkdir(parents=True, exist_ok=True)
    rl = RunLogger("06_package_release", args.logdir)
    rl.add_params(name=args.name, decoy=args.decoy,
                  append_reference=args.append_reference,
                  drop_non_novel=args.drop_non_novel, drop_nmd=args.drop_nmd,
                  missed_cleavages=args.missed_cleavages)
    rl.add_input("fasta", args.fasta)
    rl.add_input("uniprot", args.uniprot)

    # ---- 1. load + cross-class dedup ----------------------------------
    # Stage 2 deduplicates identical sequences within a class before this
    # stage ever sees them, dropping the locus of every merged record. The
    # sidecar it writes is the only way to recover them, and without it the
    # provenance graph is missing exactly the entries that most need it.
    stage2_merges = {}
    _side = Path(str(args.fasta) + ".merged_loci.tsv")
    if _side.is_file():
        with open(_side, encoding="utf-8") as fh:
            for m in csv.DictReader(fh, delimiter="	"):
                k = (m.get("kept_locus", ""), m.get("kept_transcript", ""))
                stage2_merges.setdefault(k, []).append(m)

    entries = list(read_fasta(Path(args.fasta)))
    rl.log.info("read %d entries", len(entries))
    by_seq: dict[str, list[tuple[str, dict]]] = defaultdict(list)
    for hdr, seq in entries:
        if seq:
            by_seq[seq].append((hdr, kv(hdr)))
    rl.log.info("%d distinct sequences (%d duplicates merged)",
                len(by_seq), len(entries) - len(by_seq))
    rl.count("input_entries", len(entries))
    rl.count("distinct_sequences", len(by_seq))

    # ---- 2. reference peptide space -----------------------------------
    db = UniProtDB.load(args.uniprot, logger=rl.log)
    rl.log.info("digesting reference proteome (this is the slow step) ...")
    ref_space = reference_peptide_space(
        (e.sequence for e in db.entries.values()),
        missed_cleavages=args.missed_cleavages,
        min_len=args.min_pep_len, max_len=args.max_pep_len)
    rl.log.info("reference peptide space: %d distinct tryptic peptides "
                "(I/L equated)", len(ref_space))
    rl.count("reference_peptides", len(ref_space))

    # ---- 3. build the release records ---------------------------------
    rows = []
    provenance = []
    peptide_rows = []
    kept: list[tuple[str, str]] = []
    stats = Counter()
    for seq, hits in by_seq.items():
        classes = [h[1].get("VT", "?") for h in hits]
        primary = min(classes,
                      key=lambda c: (CLASS_PRIORITY.index(c)
                                     if c in CLASS_PRIORITY else 99))
        hdr = next(h[0] for h in hits if h[1].get("VT") == primary)
        meta = kv(hdr)

        nov = novel_peptides(seq, ref_space, args.missed_cleavages,
                             args.min_pep_len, args.max_pep_len)
        pos = meta.get("POS")
        span = variant_spanning_peptides(
            seq, int(pos) if pos and pos.isdigit() else None, nov)
        n_all = len(digest(seq, args.missed_cleavages,
                           args.min_pep_len, args.max_pep_len))

        nmd_flag = meta.get("NMD", "")
        if args.drop_nmd and nmd_flag == "likely":
            stats["dropped_nmd"] += 1
            continue
        if args.drop_non_novel and not nov and primary != "REFERENCE":
            stats["dropped_no_novel_peptide"] += 1
            continue

        also = sorted(set(classes) - {primary})
        new_hdr = hdr
        if also:
            new_hdr += " ALSO=" + ",".join(also)
        new_hdr += f" NOVELPEP={len(nov)} VARPEP={len(span)} NPEP={n_all}"
        kept.append((new_hdr, seq))
        stats[f"kept.{primary}"] += 1
        if not nov and primary != "REFERENCE":
            stats["kept_but_no_novel_peptide"] += 1

        row = {
            "seq_id": new_hdr.split()[0].lstrip(">"),
            "variant_class": primary,
            "also_classes": ";".join(also),
            "consequence": meta.get("CSQ", ""),
            "gene": meta.get("GN", ""),
            "transcript": meta.get("TX", ""),
            "uniprot_accession": meta.get("UP", ""),
            "protein_change": meta.get("PC", ""),
            "locus": meta.get("LOC", ""),
            "variant_position_aa": meta.get("POS", ""),
            "novel_residue_span": meta.get("NOVEL", ""),
            "nmd": nmd_flag,
            "evidence_source": meta.get("SRC", ""),
            "source_confidence": meta.get("CONF", ""),
            "uniprot_residue_check": meta.get("QC", ""),
            "protein_length": len(seq),
            "n_tryptic_peptides": n_all,
            "n_novel_peptides": len(nov),
            "n_variant_spanning_novel": len(span),
            "example_novel_peptide": sorted(span or nov)[0] if (span or nov) else "",
            "notes": meta.get("NOTE", ""),
        }
        if not args.no_sequence_column:
            row["sequence"] = seq
        # -- M7a: the provenance graph ------------------------------
        # `hits` holds every stage-2 record that produced this exact
        # sequence. Cross-class dedup keeps one header and discards the
        # rest, which loses the locus of every merged variant - two
        # different DNA changes encoding the same residue collapse to one
        # entry and one LOC. Recording them here is the only way to ask
        # "which calls produced this sequence" without re-running.
        # -- M7b: peptide-level provenance ---------------------------
        # After a search returns a hit, the question is "which variant
        # explains this peptide", and answering it from the FASTA alone
        # means re-deriving the digest by hand. `span` is already the set
        # of novel peptides covering the variant residue.
        for pep in sorted(nov):
            peptide_rows.append({
                "peptide": pep,
                "seq_id": new_hdr.split()[0].lstrip(">"),
                "gene": meta.get("GN", ""),
                "transcript": meta.get("TX", ""),
                "variant_class": primary,
                "consequence": meta.get("CSQ", ""),
                "spans_variant": "yes" if pep in span else "no",
                "protein_change": meta.get("PC", ""),
                "loci": ";".join(
                    sorted({h[1].get("LOC", "") for h in hits
                            if h[1].get("LOC")})),
            })

        provenance.append({
            "seq_id": row["seq_id"],
            "sha256": hashlib.sha256(seq.encode()).hexdigest(),
            "length": len(seq),
            "variant_class": primary,
            "also_classes": also,
            "gene": meta.get("GN", ""),
            "transcript": meta.get("TX", ""),
            "n_variants": len(hits),
            "variants": ([
                {"seq_id": m["merged_seq_id"],
                 "variant_class": m["merged_variant_class"],
                 "consequence": "",
                 "locus": m["merged_locus"],
                 "transcript": m.get("merged_transcript", ""),
                 "protein_change": m["merged_protein_change"]}
                for h in hits
                for m in stage2_merges.get(
                    (h[1].get("LOC", ""), h[1].get("TX", "")), [])
            ]) + [
                {"seq_id": h[0].split()[0].lstrip(">"),
                 "variant_class": h[1].get("VT", ""),
                 "consequence": h[1].get("CSQ", ""),
                 "locus": h[1].get("LOC", ""),
                 "transcript": h[1].get("TX", ""),
                 "protein_change": h[1].get("PC", "")}
                for h in hits],
        })
        rows.append(row)

    # ---- 4. reference + decoys ----------------------------------------
    if args.append_reference:
        have = {s for _, s in kept}
        n_app = 0
        for e in db.entries.values():
            if e.sequence and e.sequence not in have:
                kept.append((e.header(), e.sequence))
                n_app += 1
        rl.log.info("appended %d reference proteins", n_app)
        stats["appended_reference"] = n_app

    target = out / f"{args.name}.target.fasta"
    with open(target, "w", encoding="utf-8") as fh:
        for h, s in kept:
            fh.write(h + "\n" + s + "\n")
    rl.add_output("target_fasta", target)

    final = target
    if args.decoy != "none":
        make = DECOY_METHODS[args.decoy]
        final = out / f"{args.name}.target_decoy.fasta"
        with open(final, "w", encoding="utf-8") as fh:
            for h, s in kept:
                fh.write(h + "\n" + s + "\n")
            for h, s in kept:
                first, *rest = h[1:].split(" ", 1)
                fh.write(f">{args.decoy_prefix}{first}"
                         + (" " + rest[0] if rest else "")
                         + f" DECOY={args.decoy}\n")
                fh.write(make(s) + "\n")
        rl.add_output("target_decoy_fasta", final)
        stats["decoy_entries"] = len(kept)

    if args.split_by_class:
        bc = out / "by_class"
        bc.mkdir(exist_ok=True)
        per: dict[str, list[tuple[str, str]]] = defaultdict(list)
        for h, sq in kept:
            m = re.search(r"\bVT=(\S+)", h)
            if m:
                cls = m.group(1)
            elif h.startswith(">sp|") or h.startswith(">tr|"):
                # Appended reference-proteome entries keep their pristine
                # UniProt header - no VT= - so that the file stays
                # byte-comparable with the supplied template. They are the
                # reference proteome, not unclassified.
                cls = "REFERENCE_PROTEOME"
            else:
                cls = "UNCLASSIFIED"
            per[cls].append((h, sq))
        for cls, items in sorted(per.items()):
            fp = bc / f"{args.name}.{cls}.fasta"
            with open(fp, "w", encoding="utf-8") as fh:
                for h, sq in items:
                    fh.write(h + "\n" + sq + "\n")
            rl.log.info("by_class/%s : %d sequences", fp.name, len(items))
            stats[f"split.{cls}"] = len(items)

        # An index so the filenames do not need decoding
        idx = ["# Variant-type FASTA files", "",
               f"Each file below is a subset of `{args.name}.target.fasta`, "
               "carrying the same headers. Together they contain every "
               "sequence in the combined file, with no overlap.", ""]
        for cls, items in sorted(per.items(),
                                 key=lambda kv: (CLASS_PRIORITY.index(kv[0])
                                                 if kv[0] in CLASS_PRIORITY
                                                 else 99)):
            title, desc = CLASS_DESC.get(cls, (cls, ""))
            idx.append(f"## `{args.name}.{cls}.fasta` — {title}")
            idx.append("")
            idx.append(f"{len(items):,} sequences. Header field: `VT={cls}`.")
            idx.append("")
            idx.append(desc)
            idx.append("")
        (bc / "INDEX.md").write_text("\n".join(idx), encoding="utf-8")
        rl.log.info("wrote by_class/INDEX.md")

    # M7b: one row per novel peptide, naming the variants that explain it.
    # This is what a proteomics group needs once a search returns a hit.
    pep_path = out / "tables" / "peptide_provenance.tsv"
    pep_path.parent.mkdir(parents=True, exist_ok=True)
    if peptide_rows:
        with open(pep_path, "w", newline="", encoding="utf-8") as fh:
            w = csv.DictWriter(fh, fieldnames=list(peptide_rows[0]),
                               delimiter="\t", lineterminator="\n")
            w.writeheader()
            w.writerows(peptide_rows)
        rl.add_output("peptide_provenance", pep_path)
        rl.count("peptide_provenance_rows", len(peptide_rows))
        n_span = sum(1 for r in peptide_rows if r["spans_variant"] == "yes")
        rl.log.info("peptide provenance: %d novel peptides, %d spanning a "
                    "variant residue", len(peptide_rows), n_span)

    # M7a: one record per output sequence, listing every input record that
    # produced it. JSON Lines so it streams and greps.
    prov_path = out / "tables" / "provenance.jsonl"
    prov_path.parent.mkdir(parents=True, exist_ok=True)
    n_merged = sum(1 for p in provenance if p["n_variants"] > 1)
    with open(prov_path, "w", newline="\n", encoding="utf-8") as fh:
        for rec in provenance:
            fh.write(json.dumps(rec, sort_keys=True) + "\n")
    rl.add_output("provenance", prov_path)
    rl.count("provenance_records", len(provenance))
    rl.count("provenance_merged_sequences", n_merged)
    rl.log.info("provenance: %d sequences, %d of them from more than one "
                "input record", len(provenance), n_merged)

    table = out / f"{args.name}.entries.tsv"
    if rows:
        with open(table, "w", newline="", encoding="utf-8") as fh:
            w = csv.DictWriter(fh, fieldnames=list(rows[0]), delimiter="\t",
                               lineterminator="\n")
            w.writeheader()
            w.writerows(rows)
    rl.add_output("entry_table", table)

    # per-class summary, so the composition is legible without a spreadsheet
    summ = out / f"{args.name}.summary_by_class.tsv"
    agg: dict[str, dict] = {}
    for r in rows:
        c = r["variant_class"]
        a = agg.setdefault(c, {"variant_class": c, "n_entries": 0,
                               "n_genes": set(), "n_with_novel_peptide": 0,
                               "n_novel_peptides_total": 0,
                               "n_nmd_likely": 0, "total_residues": 0})
        a["n_entries"] += 1
        if r["gene"]:
            a["n_genes"].add(r["gene"])
        if r["n_novel_peptides"]:
            a["n_with_novel_peptide"] += 1
        a["n_novel_peptides_total"] += r["n_novel_peptides"]
        if r["nmd"] == "likely":
            a["n_nmd_likely"] += 1
        a["total_residues"] += r["protein_length"]
    with open(summ, "w", newline="", encoding="utf-8") as fh:
        cols = ["variant_class", "n_entries", "n_genes", "n_with_novel_peptide",
                "pct_with_novel_peptide", "n_novel_peptides_total",
                "n_nmd_likely", "mean_protein_length"]
        w = csv.DictWriter(fh, fieldnames=cols, delimiter="\t",
                           lineterminator="\n")
        w.writeheader()
        for c in sorted(agg, key=lambda x: (CLASS_PRIORITY.index(x)
                                            if x in CLASS_PRIORITY else 99)):
            a = agg[c]
            w.writerow({
                "variant_class": c, "n_entries": a["n_entries"],
                "n_genes": len(a["n_genes"]),
                "n_with_novel_peptide": a["n_with_novel_peptide"],
                "pct_with_novel_peptide":
                    f"{100*a['n_with_novel_peptide']/a['n_entries']:.1f}",
                "n_novel_peptides_total": a["n_novel_peptides_total"],
                "n_nmd_likely": a["n_nmd_likely"],
                "mean_protein_length":
                    round(a["total_residues"] / a["n_entries"], 1),
            })
    rl.add_output("summary_by_class", summ)

    for k, v in stats.items():
        rl.count(k, v)

    # ---- 5. extras, methods, manifest ---------------------------------
    for x in args.extra_file:
        p = Path(x)
        if p.is_dir():
            shutil.copytree(p, out / p.name, dirs_exist_ok=True)
        elif p.exists():
            shutil.copy2(p, out / p.name)

    n_novel0 = stats["kept_but_no_novel_peptide"]
    n_kept = sum(v for k, v in stats.items() if k.startswith("kept."))
    n_ref_entries = stats.get("kept.REFERENCE", 0)
    n_var_entries = n_kept - n_ref_entries
    n_appended = stats.get("appended_reference", 0)
    n_dropped_nn = stats.get("dropped_no_novel_peptide", 0)
    n_dropped_nmd = stats.get("dropped_nmd", 0)
    methods = f"""# {args.name} — methods

## What this is

A protein sequence database for HCC1395, built from the high-confidence
variant package: somatic SNVs and indels, A-to-I RNA-editing sites, gene
fusions, and long-read alternative-splicing events. Every entry carries
its variant type in the header.

## Format

UniProt/SwissProt grammar, matching the supplied reference proteome:

    >vr|<id>|<GENE>_HUMAN_<TYPE> <description> OS=Homo sapiens OX=9606 GN=<gene> VT=<type> ...

Sequences are unwrapped, one line per entry. Reference entries use the
standard `sp|` prefix; variant entries use `vr|`, so a search engine can
separate the two on the database field alone.

Header fields: `VT` variant type, `CSQ` consequence, `TX` transcript,
`PC` protein change, `LOC` genomic locus, `POS` variant residue,
`NOVEL` novel residue span, `SRC` evidence source, `CONF` source
confidence, `QC` UniProt residue check, `NMD` nonsense-mediated-decay
prediction, `NOVELPEP` count of tryptic peptides absent from the
reference proteome, `VARPEP` how many of those span the variant residue,
`NPEP` total tryptic peptides, `ALSO` other variant classes producing an
identical sequence.

## Construction

Reference: GRCh38 primary assembly, GENCODE v44 annotation.

Variants are applied to the mature transcript rather than to genomic
sequence, so one code path serves DNA variants and RNA editing: an
A-to-I edit is indistinguishable from a genomic A>G at transcript level.
Translation runs from the annotated start codon to the first stop;
frameshifts translate past the annotated stop into the 3' UTR.

Fusions take the 5' partner's transcript to the breakpoint and the 3'
partner's from it, snapping intronic breakpoints to the flanking exon
boundary. Both frame flags are reported separately: whether the 5'
partner's codon boundary is intact, and whether the 3' partner continues
in its own native frame.

Splicing events are resolved by junction matching against annotated
GENCODE transcripts; only where no annotated transcript carries the
junction is an isoform constructed, and those entries are flagged.

## Validation

Reference proteins translated by this pipeline were compared with
GENCODE's own translations of the same transcript ids: **100% identical**.
That single check validates exon assembly, CDS offset, strand handling
and the codon table together, independently of which isoform any source
considers canonical.

Comparison against UniProt canonical gives a lower nominal figure because
UniProt and GENCODE curate canonical isoforms independently and often
choose different start codons; those cases are reported as
`isoform_extension` or `offset_isoform` rather than as errors.

Biological positive controls recovered from the RNA-editing input:
GRIA2 Q607R, NEIL1 K242R, BLCAP Y2C, CDK13 Q103R, COG3 I635V — all
canonical ADAR recoding sites.

Unit and integration tests: 54 assertions against a synthetic reference
whose expected proteins are known by construction.

## Using this database

- **Class-specific FDR.** Variant peptides need FDR estimated separately
  from canonical peptides; a single global FDR over a database this size
  understates the error rate for the variant subset. The `VT=` field
  exists so the class label survives into the search output.
- **Decoys.** {"Included, generated by " + args.decoy + "." if args.decoy != "none" else "Not included — generate them with the same tool and settings you use for the reference database."}
- **Contaminants.** Append a cRAP contaminant list before searching.
- **NMD.** Entries flagged `NMD=likely` carry a premature stop more than
  50 nt upstream of the last exon-exon junction and are probably degraded
  rather than translated. {"They were dropped." if args.drop_nmd else "They are retained; filter on the flag if you want only translated proteoforms."}
- **Novelty.** {n_novel0} retained entries contribute no tryptic peptide
  absent from the reference proteome. They enlarge the search space
  without adding evidence and can be removed with `--drop-non-novel`.

## Filtering applied

| filter | entries removed |
|---|---:|
| synonymous variants (identical to reference) | applied at stage 2 |
| contributing no novel tryptic peptide | {n_dropped_nn if args.drop_non_novel else "not applied"} |
| NMD=likely | {n_dropped_nmd if args.drop_nmd else "not applied"} |
| cross-class duplicate sequences | {stats.get("input_entries", 0) - stats.get("distinct_sequences", 0)} |

## Contents

`{target.name}` — combined target database, all variant types in one file:
{n_var_entries} variant entries + {n_ref_entries} wild-type counterparts of
the affected transcripts{f" + {n_appended} appended reference proteins" if n_appended else ""}
= {n_kept + n_appended} sequences total
{"`" + final.name + "` — the same, concatenated with decoys" if args.decoy != "none" else ""}
{"`by_class/` — one FASTA per variant type, same entries and headers as the combined file; see by_class/INDEX.md for what each file contains" if args.split_by_class else ""}
`{table.name}` — one row per entry: class, gene, transcript, protein
change, locus, NMD flag, peptide counts and the sequence itself
`{summ.name}` — per-class composition summary
`MANIFEST.txt` — SHA-256 of every file here

All inputs, parameters, environment and checksums for each pipeline stage
are recorded in the `logs/*.provenance.json` files.
"""
    (out / "METHODS.md").write_text(methods, encoding="utf-8")

    man = ["# MANIFEST — {}".format(args.name), ""]
    for f in sorted(out.rglob("*")):
        if f.is_file() and f.name != "MANIFEST.txt":
            man.append(f"{sha256(f)}  {f.relative_to(out)}  "
                       f"({f.stat().st_size:,} bytes)")
    (out / "MANIFEST.txt").write_text("\n".join(man) + "\n", encoding="utf-8")

    rl.close()
    print(f"\nrelease written to {out}/")
    for k in sorted(stats):
        print(f"  {k:34s} {stats[k]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
